blank_issues_enabled: true
contact_links:
  - name: 🙋🏾 Question
    url: https://github.com/email-for-indiehackers/.github/discussions/new/choose
    about: Use this link to submit your question to GitHub Discussions.
